### ISSUE TITLE
Login locale URL issue in 4.5

### ISSUE THREAD

**Issue by mrbrdo** [spree/spree_legacy_frontend#41]
@wjwitek I'm not sure if all your work is already included in 4.5 versions of gems, but I was testing around with spree_starter and v4.5 legacy frontend (so '4.5' in Gemfile for all the spree gems), and I found this situation:
- choose default language (the one that doesn't have a prefix in the URL)
- go to login page
- now click the globe icon and change the language to a non-default one
- in my case it will redirect to `/de-DE/login` but that route does not exist

Note that if you switch language somewhere else and then click on the login link, that works fine (`/login?locale=de-DE`). Same thing also happens with the signup link.
In https://github.com/spree/spree_auth_devise/pull/570 you link to my PR https://github.com/spree/spree_auth_devise/pull/570 - does that mean you have not found another solution to this problem? As my PR itself seems mostly obsolete apart from this issue.

**Comment by wjwitek** [comment]
@mrbrdo Since those changes were made after 4.5 release they are not include in it. The problem is the changes I've made in spree_legacy_frontend do not work withour changes made to spree_auth_device (https://github.com/spree/spree_auth_devise/pull/570, altough with different solution), so you would have to specify in Gemfile for it to be pulled from github as well. But I see now how that may cause issues if someone gets the github version of only one of them as it's not specified anywhere.
And in general all links connected to account should now also follow the convention of /locale/path.

**Comment by mrbrdo** [comment]
@wjwitek thanks for the explanation, so I guess if using main branch of both gems, or in the next version, it should be fixed.
